name: sanitizer tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build_wheels:
    runs-on: ubuntu-22.04
    name: Sanitizer tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: Build with sanitizers
        run: |
          python -m pip install nanobind
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebug -DUSE_SANITIZERS=ON
          cmake --build build
      - name: Test with sanitizers
        run: |
          cd build/src
          ASAN_OPTIONS="detect_leaks=0" LD_PRELOAD="$(gcc -print-file-name=libasan.so)" python -m pytest ../../tests/
